### ISSUE TITLE
Problems parsing config file

### ISSUE THREAD

**Issue by darkith** [philiphoy/icingaweb2-module-graphite#13]
Running Icingaweb2 RC1 on Ubuntu 12.04.5
Icingaweb2 is having problems parsing the config file.
I copied the default text that comes up when click on the Modules->Configuration->Graphite-Configuration pane into /etc/icingaweb2/modules/graphite, but reloading the configuration pane throws a syntax error, unexpected '=' in /etc/icingaweb2/modules/graphite/config.ini on line 4, and the plugin doesn't function (no graphs displayed in host/service views)

```
#0 [internal function]: Icinga\Application\{closure}(2, 'syntax error, u...', '/usr/share/php/...', 316, Array)
#1 /usr/share/php/Icinga/Application/Config.php(316): parse_ini_file('/etc/icingaweb2...', true)
#2 /usr/share/php/Icinga/Application/Config.php(419): Icinga\Application\Config::fromIni('/etc/icingaweb2...')
#3 /usr/share/php/Icinga/Web/Controller/ModuleActionController.php(50): Icinga\Application\Config::module('graphite')
#4 /usr/share/icingaweb2/modules/graphite/application/controllers/ConfigController.php(21): Icinga\Web\Controller\ModuleActionController->Config()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Graphite_ConfigController->indexAction()
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Dispatcher/Standard.php(303): Zend_Controller_Action->dispatch('indexAction')
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Zend_Controller_Dispatcher_Standard->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(154): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(111): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#11 {main}
```

It looks like it can't parse service_name_template unless it's followed by a blank line or comment.
Same appears to apply to host_name_template.
Ensuring there's a comment or blank line after each of these two parameters allows the plugin to function correctly.

i.e.:
This fails to parse:

```
service_name_template = env1.$HOSTNAME$.$SERVICEDESC$
host_name_template = env1.$HOSTNAME$
graphite_args_template = ...
```

This works:

```
service_name_template = env1.$HOSTNAME$.$SERVICEDESC$

host_name_template = env1.$HOSTNAME$
;comment or blank line here as well
graphite_args_template = ...
```

**Comment by TheBigLee** [comment]
I was able to solve this issue by enclosing the value of the service_name_template and host_name_template in quotes.
eg: 

```
service_name_template = "env1.$HOSTNAME$.$SERVICEDESC$"
host_name_template = "env1.$HOSTNAME$"
graphite_args_template = ...
```

**Comment by philiphoy** [comment]
Altered configuration hint to be in line with @Bigluu's suggestion e517a8886c552c08ce8073b67bc9d93328be3711
